### PR TITLE
Fix issue #85 product feature description alignment

### LINKED ISSUE #85: product.php please fixing style
please make only row 132 and 136 text center for SP layout.
right now .feature__description: text-center which makes the whole feature__description text-center.

### PR DESCRIPTION
**Pull request by antoine-boue**
Closes #85

### CODE REVIEW

File: views/pages/product.php [hunk 1]
```diff
@@ -296,7 +296,8 @@
             <th class="table__cell table__cell--header">備考</th>
             <td class="table__cell">
               <p>■組み立て式:プラスドライバーをご用意ください。</p>
-              <p>【取扱説明書】はこちら <a class="link" href="../../assets/pdf/instruction.pdf" target="_blank">(通常サイズ)</a> <a class="link" href="../../assets/pdf/instruction-Lg.pdf" target="_blank">(大型サイズ)</a></p>
+              <p>【取扱説明書】はこちら <a class="link" href="../../assets/pdf/instruction.pdf" target="blank">(通常サイズ)</a> <a class="link" href="../../assets/pdf/instruction-Lg.pdf" download="取り扱い説明書_
```
Comment (windresistance) [inline views/pages/product.php:299]: You don't need the "_" here?

**Review by windresistance — APPROVED** [review]
